module.exports = {
  addSites: require("./addSites"),
  addTourist: require("./addTourist"),
  apply: require("./apply"),
  checkMyAppliedStatus: require("./checkMyAppliedStatus"),
  copy: require("./copy"),
  countMyTourData: require("./countMyTourData"),
  countPublicData: require("./countPublicData"),
  create: require("./create"),
  deleteSite: require("./deleteSite"),
  deleteSiteOverLimitDay: require("./deleteSiteOverLimitDay"),
  deleteTour: require("./deleteTour"),
  deleteTourist: require("./deleteTourist"),
  edit: require("./edit"),
  getAppliedList: require("./getAppliedList"),
  getMyAppliedTour: require("./getMyAppliedTour"),
  getMyTourList: require("./getMyTourList"),
  getPrivateTourDetail: require("./getPrivateTourDetail"),
  getPublicTourDetail: require("./getPublicTourDetail"),
  search: require("./search"),
};
