module.exports = {
  checkLikeOrCollection: require("./checkLikeOrCollection"),
  collectSite: require("./collectSite"),
  countMyCollections: require("./countMyCollections"),
  countMySiteData: require("./countMySiteData"),
  countPublicData: require("./countPublicData"),
  createNewSite: require("./createNewSite"),
  deleteSite: require("./deleteSite"),
  editSite: require("./editSite"),
  getMyCollections: require("./getMyCollections"),
  getMySiteDetail: require("./getMySiteDetail"),
  getMySiteList: require("./getMySiteList"),
  getOtherSitesOfAuthor: require("./getOtherSitesOfAuthor"),
  getPublicSiteById: require("./getPublicSiteById"),
  likeSite: require("./likeSite"),
  removeCollection: require("./removeCollection"),
  removeLike: require("./removeLike"),
  searchSite: require("./searchSite"),
};
